### ISSUE TITLE
Drawer icons to-do

### ISSUE THREAD

**Issue by Madis0** [Madis0/smartlaunchertemplate#5]
- [ ] Fix ic_market
- [ ] Make topmost icons smaller
- [ ] Make them all gray for a "softer" look?
